type: "transformation"
version:
pipeline:
  components:
    Online Orders:
      type: "table-input"
      parameters:
        componentName: "Online Orders"
        database: "DEMODATABASE"
        schema: "DEMOSCHEMA"
        targetTable: "ONLINE_ORDER"
        columnNames:
        - "CUSTOMER_ID"
        - "CUSTOMER_NAME"
        - "ORDER_DATE"
        - "AMOUNT"
    Instore Orders:
      type: "table-input"
      parameters:
        componentName: "Instore Orders"
        database: "DEMODATABASE"
        schema: "DEMOSCHEMA"
        targetTable: "INSTORE_ORDER"
        columnNames:
        - "CUSTOMER_ID"
        - "CUSTOMER_NAME"
        - "ORDER_DATE"
        - "AMOUNT"
    Combine Orders:
      type: "unite"
      sources:
      - "Instore Orders"
      - "Online Orders"
      parameters:
        componentName: "Combine Orders"
        method: "Overlapping Columns"
        castTypes: "Yes"
        addSourceComponentColumn: "No"
        removeDuplicates: "Yes"
    Filter Low Amounts:
      type: "filter"
      sources:
      - "Combine Orders"
      parameters:
        componentName: "Filter Low Amounts"
        filterConditions:
        - - "AMOUNT"
          - "Is"
          - "Less than"
          - "2000"
        combineCondition: "And"
    Save Results:
      type: "rewrite-table"
      sources:
      - "Filter Low Amounts"
      parameters:
        componentName: "Save Results"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "UNION_FILTERED_RESULTS"
design:
  components:
    Online Orders:
      position:
        x: 0
        "y": 0
      tempMetlId:
    Instore Orders:
      position:
        x: 0
        "y": 100
      tempMetlId:
    Combine Orders:
      position:
        x: 160
        "y": 60
      tempMetlId:
    Filter Low Amounts:
      position:
        x: 320
        "y": 60
      tempMetlId:
    Save Results:
      position:
        x: 480
        "y": 60
      tempMetlId:
